from selenium.webdriver.common.by import By


class OrderPageLocators:
    name_field = (By.XPATH, '//div[2]/div[1]/input')
    second_name_field = (By.XPATH, '//div[2]/input')
    address_field = (By.XPATH, '//div[3]/input')
    metro_station_field = (By.XPATH, '//div[4]/div/div/input')
    metro_list = (By.XPATH, "//ul/li[4]")
    metro_list_2 = (By.XPATH, "//ul/li[15]")
    telephone_field = (By.XPATH, '//div[5]/input')
    next_button = (By.XPATH, "//button[text() = 'Далее']")
    delivery_time_field = (By.XPATH, "//div[2]/div[1]/div[1]/div/input")
    calendar_field = (By.XPATH, "//div[3][text () = '16']")
    calendar_field_other_day = (By.XPATH, "//div[7][text () = '20']")
    period_field = (By.XPATH, '//div[2]/div[2]/div[2]/div[1]/div[1]')
    period_field_three_days = (By.XPATH, '//div[2]/div[3]')
    period_field_five_days = (By.XPATH, '//div[2]/div[5]')
    scooter_color_black = (By.XPATH, '//label[1]/input')
    scooter_color_gray = (By.XPATH, '//label[2]/input)')
    note_field = (By.XPATH, '//div[4]/input')
    order_button = (By.XPATH, '//div[3]/button[2]')
    order_complete_button = (By.XPATH, "//button[2][text() = 'Да']")
    order_status_button = (By.XPATH, "//button[text() = 'Посмотреть статус']")
    order_complete_text = (By.XPATH, "//div[5]/div[1][text() = 'Заказ оформлен']")
    main_order_button = (By.XPATH, 'html/body/div/div/div[1]/div[1]/div[2]/button[1]')
    main_order_button_two = (By.XPATH, 'html/body/div/div/div[1]/div[4]/div[2]/div[5]/button')
    scooter_image = (By.XPATH, "//a[2]/img")
    yandex_image = (By.XPATH, "//a[1]/img")